USE publications;

SELECT  `TITLE ID`,
	    `AUTHOR ID`,
        SUM(ROYALTY)
FROM

(SELECT  T.TITLE_ID AS `TITLE ID`,
	    TA.AU_ID AS `AUTHOR ID`,
        t.price * s.qty * t.royalty / 100 * ta.royaltyper / 100 AS 'ROYALTY'

FROM TITLES AS T 
INNER JOIN TITLEAUTHOR AS TA
ON T.TITLE_ID = TA.TITLE_ID
INNER JOIN SALES AS S
ON T.TITLE_ID = S.TITLE_ID) AS ROYALTIES
GROUP BY `TITLE ID`, `AUTHOR ID`;
